[versions]
# ================== APP ================== #
# Build details
compileSdk = "35"
targetSdk = "35"
minSdk = "26"
versionCode = "55"
versionName = "2.3.1"

# Libraries
composeBom = "2025.03.00"
firebaseBom = "33.11.0"
koinBom = "4.0.2"

accompanistPermissions = "0.37.2"
androidCredentials = "1.5.0"
androidDataStore = "1.1.3"
androidLifecycle = "2.8.7"
androidMedia = "1.5.1"
androidTestEspresso = "3.6.1"
androidTestJunit = "1.2.1"
coil = "2.7.0"
composeNavigation = "2.8.9"
googleid = "1.1.1"
haze = "1.3.1"
junit = "4.13.2"
kotlinCore = "1.15.0"
ktor = "3.1.0"
mapsCompose = "6.4.2"
playServicesLocation = "21.3.0"
playServicesMaps = "19.1.0"
protobuf = "4.30.1"

# Plugins
androidGradlePlugin = "8.8.2"
firebaseCrashlyticsPlugin = "3.0.3"
googleMapsplatformPlugin = "2.0.1"
googleProtobufPlugin = "0.9.4"
googleServicesPlugin = "4.4.2"
kotlinAndroidPlugins = "2.1.10"

# ================ SERVER ================= #
# Libraries
firebaseAdmin = "9.5.0"
mockito = "5.4.0"
testcontainers = "2.0.2"

# Plugins
kotlinJvmPlugins = "2.1.10"
springBoot = "3.5.4"
springManager = "1.1.7"

# ================ SHARED ================= #
kotlinSerializationJson = "1.8.0"
ktlintPlugin = "12.2.0"

# ================= TYPES ================= #
jakartaPersistence = "3.2.0"

[libraries]
# ================== APP ================== #
android-credentials-base = { group = "androidx.credentials", name = "credentials", version.ref = "androidCredentials" }
android-credentials-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidCredentials" }
android-dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "androidDataStore" }
android-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
android-media-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidMedia" }
android-media-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidMedia" }
android-media-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidMedia" }
android-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidTestEspresso" }
android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidTestJunit" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-ui-base = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling-base = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
google-libraries-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
google-libraries-maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "mapsCompose" }
google-libraries-protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
google-libraries-protobuf-compiler = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
google-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
google-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
haze-base = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
koin-compose-base = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-compose-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation" }
kotlin-core = { group = "androidx.core", name = "core-ktx", version.ref = "kotlinCore" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }

# ================ SERVER ================= #
firebase-admin = { group = "com.google.firebase", name = "firebase-admin", version.ref = "firebaseAdmin" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-mariadb = { group = "org.testcontainers", name = "testcontainers-mariadb", version.ref = "testcontainers" }

# ================= TYPES ================= #
jakarta-persistence = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakartaPersistence" }

# ================= SHARED ================ #
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

[plugins]
# ================== APP ================== #
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref="firebaseCrashlyticsPlugin" }
google-mapsplatform = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleMapsplatformPlugin" }
google-protobuf = { id = "com.google.protobuf", version.ref = "googleProtobufPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugins" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinAndroidPlugins" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }

# ================ SERVER ================= #
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvmPlugins" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinJvmPlugins" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlinJvmPlugins" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-manager = { id = "io.spring.dependency-management", version.ref = "springManager" }

# ================ SHARED ================= #
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinAndroidPlugins" }
